# Generated by Django 5.2.13 on 2026-05-18 18:20

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BuildingSuggestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=200, verbose_name="Название здания"),
                ),
                (
                    "city",
                    models.CharField(
                        choices=[
                            ("msk", "Москва"),
                            ("spb", "Санкт-Петербург"),
                            ("vlg", "Волгоград"),
                            ("other", "Другой город"),
                        ],
                        default="other",
                        max_length=50,
                        verbose_name="Город",
                    ),
                ),
                ("address", models.CharField(max_length=300, verbose_name="Адрес")),
                ("description", models.TextField(verbose_name="Описание здания")),
                (
                    "suggested_by",
                    models.CharField(max_length=200, verbose_name="Ваше имя"),
                ),
                (
                    "suggested_email",
                    models.EmailField(max_length=254, verbose_name="Ваш Email"),
                ),
                (
                    "suggested_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="Дата предложения",
                    ),
                ),
                (
                    "is_processed",
                    models.BooleanField(default=False, verbose_name="Обработано"),
                ),
                (
                    "processed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Дата обработки"
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, verbose_name="Комментарий модератора"),
                ),
            ],
            options={
                "verbose_name": "Предложение нового здания",
                "verbose_name_plural": "Предложения новых зданий",
                "ordering": ["-suggested_at"],
            },
        ),
        migrations.CreateModel(
            name="HistoricalBuilding",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=200, verbose_name="Название здания"),
                ),
                (
                    "short_description",
                    models.TextField(
                        max_length=500, verbose_name="Краткое описание (для списка)"
                    ),
                ),
                (
                    "full_description",
                    models.TextField(verbose_name="Полное описание для озвучки"),
                ),
                (
                    "architect",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Архитектор"
                    ),
                ),
                ("year_built", models.IntegerField(verbose_name="Год постройки")),
                ("address", models.CharField(max_length=300, verbose_name="Адрес")),
                (
                    "architectural_style",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Архитектурный стиль"
                    ),
                ),
                (
                    "tactile_features",
                    models.TextField(
                        blank=True,
                        verbose_name="Тактильные особенности (фактура стен, поручни, тактильная плитка)",
                    ),
                ),
                (
                    "sound_features",
                    models.TextField(
                        blank=True,
                        verbose_name="Звуковое окружение (фонтаны, эхо, птицы, транспорт)",
                    ),
                ),
                (
                    "accessibility_notes",
                    models.TextField(
                        blank=True,
                        verbose_name="Доступность для МГН (пандусы, лифты, широкие двери)",
                    ),
                ),
                (
                    "image_caption",
                    models.TextField(
                        blank=True,
                        null=True,
                        verbose_name="Автоматическое описание изображения (сгенерировано нейросетью)",
                    ),
                ),
                (
                    "city",
                    models.CharField(
                        choices=[
                            ("msk", "Москва"),
                            ("spb", "Санкт-Петербург"),
                            ("vlg", "Волгоград"),
                            ("other", "Другой город"),
                        ],
                        default="other",
                        max_length=50,
                        verbose_name="Город",
                    ),
                ),
                (
                    "main_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="buildings/",
                        verbose_name="Главное изображение",
                    ),
                ),
                (
                    "audio_guide",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="audio_guides/",
                        verbose_name="Аудиогид (MP3)",
                    ),
                ),
                (
                    "suggested_by",
                    models.CharField(
                        max_length=200, verbose_name="Кто предложил добавить"
                    ),
                ),
                (
                    "suggested_email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="Email для связи"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="Дата добавления",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Дата последнего обновления"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "На модерации"),
                            ("published", "Опубликовано"),
                            ("rejected", "Отклонено"),
                        ],
                        default="draft",
                        max_length=20,
                        verbose_name="Статус модерации",
                    ),
                ),
                (
                    "moderation_notes",
                    models.TextField(blank=True, verbose_name="Примечания модератора"),
                ),
            ],
            options={
                "verbose_name": "Историческое здание",
                "verbose_name_plural": "Исторические здания",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="BuildingImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to="buildings/gallery/", verbose_name="Изображение"
                    ),
                ),
                (
                    "caption",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        verbose_name="Подпись (озвучивается)",
                    ),
                ),
                (
                    "order",
                    models.IntegerField(default=0, verbose_name="Порядок отображения"),
                ),
                (
                    "building",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="buildings.historicalbuilding",
                        verbose_name="Здание",
                    ),
                ),
            ],
            options={
                "verbose_name": "Изображение здания",
                "verbose_name_plural": "Изображения зданий",
                "ordering": ["order"],
            },
        ),
    ]
